### ISSUE TITLE
KeyError: 'HdfsFileStatus'

### ISSUE THREAD

**Issue by joaodrp** [drelu/webhdfs-py#1] opened 2012-03-11 17:27 UTC
Hi,

I have a fresh clean install of HDFS 1.0.1 on ubuntu 11.10. When I try to reproduce the first part of the webhdfs-py/example it works great, but when I try to issue this part:

```
for i in webhdfs.listdir("/"):
    print str(i)
```

I get a strange error:

```
03/11/2012 05:24:00 PM - webhdfs - DEBUG - List directory: /webhdfs/v1/?op=LISTSTATUS&user.name=hadoop
03/11/2012 05:24:00 PM - webhdfs - DEBUG - HTTP Response: 200, OK
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/webhdfs/webhdfs.py", line 130, in listdir
      files = [i["localName"] for i in data_dict["HdfsFileStatus"]]
KeyError: 'HdfsFileStatus'
```

Also, i've noticed that in the web console, when I go to the contents of directory /hello-world it is empty. Although I was able to copy from it the "/hello-world/test.txt" file as in the example.

**Comment by drelu** [comment] 2012-03-11 18:50
This was caused by a minor change in the API. Should be fixed in version 0.1.06

**Closed as completed by drelu** 2012-03-11 18:50 UTC
